	bootstrapValidate('#nama_kepala_sekolah', 'required: Form wajib diisi');
	bootstrapValidate('#nama_lengkap_siswa', 'min:4:Masukkan minimal 4 karakter');
	bootstrapValidate('#nama_lengkap_siswa', 'required: Form wajib diisi');
	bootstrapValidate('#tempat_lahir', 'required: Form wajib diisi');
	bootstrapValidate('#nik', 'min:16:Masukkan NIK anda Sebanyak 16 Digit');
	bootstrapValidate('#no_telp_siswa', 'integer: Hanya boleh memasukkan angka saja!');
	bootstrapValidate('#no_telp_siswa', 'min:6: Minimal 6');
	bootstrapValidate('#no_telp_siswa', 'required: Form wajib diisi');
	bootstrapValidate('#email_siswa', 'email: Email tidak valid!');
	bootstrapValidate('#email_siswa', 'required: Form wajib diisi');
	bootstrapValidate('#alamat_siswa', 'required: Form wajib diisi');
	bootstrapValidate('#kode_pos', 'required: Form wajib diisi');
	bootstrapValidate('#kode_pos', 'integer: Hanya boleh memasukkan angka saja!');
	bootstrapValidate('#asal_sekolah', 'required: Form wajib diisi');
	bootstrapValidate('#alamat_sekolah', 'required: Form wajib diisi');
	bootstrapValidate('#username_admin', 'min:4: Masukkan minimal 4 karakter');
    bootstrapValidate('#email_admin', 'email: Masukkan email yang valid');
    bootstrapValidate('#password_admin', 'min:6: Masukkan minimal 6 karakter');
    bootstrapValidate('#confirm_password', 'matches:#password_admin:Password yang anda masukkan tidak sesuai');
    bootstrapValidate('#password_change', 'min:6: Masukkan minimal 6 karakter');
    bootstrapValidate('#confirm_password_change', 'matches:#password_change:Password yang anda masukkan tidak sesuai');
    bootstrapValidate('#longitude', 'required: Form wajib diisi');
    bootstrapValidate('#latitude', 'required: Form Wajib diisi');
    bootstrapValidate('#link_url', 'url: Masukkan Url yang valid');
    bootstrapValidate('#tahun_lulus', 'required: Form wajib diisi');
    bootstrapValidate('#nem', 'required: Form wajib diisi');
    bootstrapValidate('#agama', 'required: Form wajib diisi');